In [ ]:
# Importing necessary libraries

import pandas as pd
import numpy as np
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# reading a CSV file from a given URL into a pandas DataFrame.
df = pd.read_csv("/content/articles.csv", encoding='latin1')

In [ ]:
# Displaying the first few rows of the DataFrame
df.head()

Article  \
0  Data analysis is the process of inspecting and...   
1  The performance of a machine learning algorith...   
2  You must have seen the news divided into categ...   
3  When there are only two classes in a classific...   
4  The Multinomial Naive Bayes is one of the vari...   

                                               Title  
0                  Best Books to Learn Data Analysis  
1         Assumptions of Machine Learning Algorithms  
2          News Classification with Machine Learning  
3  Multiclass Classification Algorithms in Machin...  
4        Multinomial Naive Bayes in Machine Learning

In [ ]:
# converting the "Article" column to a list
articles = df["Article"].tolist()

In [ ]:
# printing the list of articles
print(articles)

['Data analysis is the process of inspecting and exploring data generated by a particular population to find the information needed to make decisions and draw conclusions. With the use of data in decision making, most businesses today need data analysts. So, if you want to know about the best books to learn data analysis, this article is for you. In this article, I will introduce you to some of the best books to learn data analysis.', 'The performance of a machine learning algorithm on a particular dataset often depends on whether the features of the dataset satisfies the assumptions of that machine learning algorithm. Not all machine learning algorithms have assumptions that differentiate them from each other. So, in this article, I will take you through the assumptions of machine learning algorithms.', "You must have seen the news divided into categories when you go to a news website. Some of the popular categories that you'll see on almost any news website are tech, entertainment, a

In [ ]:
# creating a TF-IDF vectorizer, and transforms the list of articles into a TF-IDF matrix
tfidf_vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf_vectorizer.fit_transform(articles)

In [ ]:
# printing the feature names
tfidf_vectorizer.get_feature_names_out()

array(['10', '13', 'agglomerative', 'ago', 'algorithm', 'algorithms',
       'analysis', 'analysts', 'analyze', 'animated', 'announced', 'api',
       'apis', 'app', 'apple', 'application', 'applications', 'apps',
       'article', 'artificial', 'assigned', 'assigning', 'assuming',
       'assumptions', 'attention', 'automatically', 'automating',
       'availability', 'available', 'awareness', 'backward', 'balanced',
       'base', 'based', 'bayes', 'beginner', 'best', 'bidirectional',
       'binary', 'birch', 'books', 'brain', 'build', 'building',
       'businesses', 'called', 'capable', 'cases', 'categories', 'cent',
       'centre', 'chatbot', 'choose', 'classes', 'classification',
       'classify', 'clustering', 'clusters', 'comes', 'common',
       'companies', 'compared', 'complex', 'computer', 'computers',
       'concept', 'conclusions', 'confused', 'connect', 'content',
       'cover', 'covers', 'create', 'creators', 'currently', 'data',
       'dataset', 'date', 'dbscan',

In [ ]:
# Displaying matrix shape
tfidf_matrix.shape

(34, 407)

In [ ]:
# Printing a portion of the TF-IDF matrix (e.g., first 5 rows and 10 columns)
print(tfidf_matrix[:5, :10])

  (0, 7)	0.16565009461657373
  (0, 6)	0.3790509426885369
  (1, 5)	0.2739926613815469
  (1, 4)	0.2387514337269739
  (3, 5)	0.19629378681482187
  (4, 4)	0.34772434687075626


In [ ]:
# Compute cosine similarity between all articles in tfidf_matrix
cosine_similarities = cosine_similarity(tfidf_matrix)

In [ ]:
# Print the cosine similarity matrix
print("Cosine Similarity Matrix:")
print(cosine_similarities)

Cosine Similarity Matrix:
[[1.         0.02858003 0.02014231 ... 0.12022323 0.00455773 0.02511323]
 [0.02858003 1.         0.07651482 ... 0.30365338 0.27795728 0.00383369]
 [0.02014231 0.07651482 1.         ... 0.08401534 0.05252305 0.03233971]
 ...
 [0.12022323 0.30365338 0.08401534 ... 1.         0.12620279 0.04275628]
 [0.00455773 0.27795728 0.05252305 ... 0.12620279 1.         0.02113943]
 [0.02511323 0.00383369 0.03233971 ... 0.04275628 0.02113943 1.        ]]


In [ ]:
# Recommendation function to recommend articles based on similarity scores
def recommend_articles(x):
    top_indices = x.argsort()[-5:][::-1]  # Get indices of top 5 most similar articles
    return ", ".join(df["Title"].iloc[top_indices].tolist())

In [ ]:
# Applying recommendation function to each row
df["Recommended Articles"] = [recommend_articles(x) for x in cosine_similarities]
df.head()

Article  \
0  Data analysis is the process of inspecting and...   
1  The performance of a machine learning algorith...   
2  You must have seen the news divided into categ...   
3  When there are only two classes in a classific...   
4  The Multinomial Naive Bayes is one of the vari...   

                                               Title  \
0                  Best Books to Learn Data Analysis   
1         Assumptions of Machine Learning Algorithms   
2          News Classification with Machine Learning   
3  Multiclass Classification Algorithms in Machin...   
4        Multinomial Naive Bayes in Machine Learning   

                                Recommended Articles  
0  Best Books to Learn Data Analysis, Best Resour...  
1  Assumptions of Machine Learning Algorithms, Us...  
2  News Classification with Machine Learning, New...  
3  Multiclass Classification Algorithms in Machin...  
4  Multinomial Naive Bayes in Machine Learning, N...

In [ ]:
# accessing the content of the "Article" column for the first row (index 1) in the DataFrame df
print(df["Article"][1])

The performance of a machine learning algorithm on a particular dataset often depends on whether the features of the dataset satisfies the assumptions of that machine learning algorithm. Not all machine learning algorithms have assumptions that differentiate them from each other. So, in this article, I will take you through the assumptions of machine learning algorithms.


In [ ]:
# accessing the title of the article in the DataFrame df at index 1
print(df["Title"][1])

Assumptions of Machine Learning Algorithms


In [ ]:
# accessing the recommended articles for the article at index 1 in the DataFrame df
print(df["Recommended Articles"][1])

Assumptions of Machine Learning Algorithms, Use Cases of Different Machine Learning Algorithms, Naive Bayes Algorithm in Machine Learning, Best Books to Learn Deep Learning, Applications of Deep Learning
